export interface RegionData {
  label: string
  value: string
  children?: RegionData[]
}

export const regionData: RegionData[] = [
  {
    label: '北京市',
    value: '北京市',
    children: [
      { label: '东城区', value: '北京市-东城区' },
      { label: '西城区', value: '北京市-西城区' },
      { label: '朝阳区', value: '北京市-朝阳区' },
      { label: '丰台区', value: '北京市-丰台区' },
      { label: '石景山区', value: '北京市-石景山区' },
      { label: '海淀区', value: '北京市-海淀区' },
      { label: '门头沟区', value: '北京市-门头沟区' },
      { label: '房山区', value: '北京市-房山区' },
      { label: '通州区', value: '北京市-通州区' },
      { label: '顺义区', value: '北京市-顺义区' },
      { label: '昌平区', value: '北京市-昌平区' },
      { label: '大兴区', value: '北京市-大兴区' },
      { label: '怀柔区', value: '北京市-怀柔区' },
      { label: '平谷区', value: '北京市-平谷区' },
      { label: '密云区', value: '北京市-密云区' },
      { label: '延庆区', value: '北京市-延庆区' },
    ],
  },
  {
    label: '上海市',
    value: '上海市',
    children: [
      { label: '黄浦区', value: '上海市-黄浦区' },
      { label: '徐汇区', value: '上海市-徐汇区' },
      { label: '长宁区', value: '上海市-长宁区' },
      { label: '静安区', value: '上海市-静安区' },
      { label: '普陀区', value: '上海市-普陀区' },
      { label: '虹口区', value: '上海市-虹口区' },
      { label: '杨浦区', value: '上海市-杨浦区' },
      { label: '闵行区', value: '上海市-闵行区' },
      { label: '宝山区', value: '上海市-宝山区' },
      { label: '嘉定区', value: '上海市-嘉定区' },
      { label: '浦东新区', value: '上海市-浦东新区' },
      { label: '金山区', value: '上海市-金山区' },
      { label: '松江区', value: '上海市-松江区' },
      { label: '青浦区', value: '上海市-青浦区' },
      { label: '奉贤区', value: '上海市-奉贤区' },
      { label: '崇明区', value: '上海市-崇明区' },
    ],
  },
  {
    label: '广东省',
    value: '广东省',
    children: [
      {
        label: '广州市',
        value: '广东省-广州市',
        children: [
          { label: '荔湾区', value: '广东省-广州市-荔湾区' },
          { label: '越秀区', value: '广东省-广州市-越秀区' },
          { label: '海珠区', value: '广东省-广州市-海珠区' },
          { label: '天河区', value: '广东省-广州市-天河区' },
          { label: '白云区', value: '广东省-广州市-白云区' },
          { label: '黄埔区', value: '广东省-广州市-黄埔区' },
          { label: '番禺区', value: '广东省-广州市-番禺区' },
          { label: '花都区', value: '广东省-广州市-花都区' },
          { label: '南沙区', value: '广东省-广州市-南沙区' },
          { label: '从化区', value: '广东省-广州市-从化区' },
          { label: '增城区', value: '广东省-广州市-增城区' },
        ],
      },
      {
        label: '深圳市',
        value: '广东省-深圳市',
        children: [
          { label: '罗湖区', value: '广东省-深圳市-罗湖区' },
          { label: '福田区', value: '广东省-深圳市-福田区' },
          { label: '南山区', value: '广东省-深圳市-南山区' },
          { label: '宝安区', value: '广东省-深圳市-宝安区' },
          { label: '龙岗区', value: '广东省-深圳市-龙岗区' },
          { label: '盐田区', value: '广东省-深圳市-盐田区' },
          { label: '龙华区', value: '广东省-深圳市-龙华区' },
          { label: '坪山区', value: '广东省-深圳市-坪山区' },
          { label: '光明区', value: '广东省-深圳市-光明区' },
        ],
      },
      { label: '珠海市', value: '广东省-珠海市' },
      { label: '汕头市', value: '广东省-汕头市' },
      { label: '佛山市', value: '广东省-佛山市' },
      { label: '韶关市', value: '广东省-韶关市' },
      { label: '湛江市', value: '广东省-湛江市' },
      { label: '肇庆市', value: '广东省-肇庆市' },
      { label: '江门市', value: '广东省-江门市' },
      { label: '茂名市', value: '广东省-茂名市' },
      { label: '惠州市', value: '广东省-惠州市' },
      { label: '梅州市', value: '广东省-梅州市' },
      { label: '汕尾市', value: '广东省-汕尾市' },
      { label: '河源市', value: '广东省-河源市' },
      { label: '阳江市', value: '广东省-阳江市' },
      { label: '清远市', value: '广东省-清远市' },
      { label: '东莞市', value: '广东省-东莞市' },
      { label: '中山市', value: '广东省-中山市' },
      { label: '潮州市', value: '广东省-潮州市' },
      { label: '揭阳市', value: '广东省-揭阳市' },
      { label: '云浮市', value: '广东省-云浮市' },
    ],
  },
  {
    label: '浙江省',
    value: '浙江省',
    children: [
      {
        label: '杭州市',
        value: '浙江省-杭州市',
        children: [
          { label: '上城区', value: '浙江省-杭州市-上城区' },
          { label: '拱墅区', value: '浙江省-杭州市-拱墅区' },
          { label: '西湖区', value: '浙江省-杭州市-西湖区' },
          { label: '滨江区', value: '浙江省-杭州市-滨江区' },
          { label: '萧山区', value: '浙江省-杭州市-萧山区' },
          { label: '余杭区', value: '浙江省-杭州市-余杭区' },
          { label: '临平区', value: '浙江省-杭州市-临平区' },
          { label: '钱塘区', value: '浙江省-杭州市-钱塘区' },
          { label: '富阳区', value: '浙江省-杭州市-富阳区' },
          { label: '临安区', value: '浙江省-杭州市-临安区' },
          { label: '桐庐县', value: '浙江省-杭州市-桐庐县' },
          { label: '淳安县', value: '浙江省-杭州市-淳安县' },
          { label: '建德市', value: '浙江省-杭州市-建德市' },
        ],
      },
      { label: '宁波市', value: '浙江省-宁波市' },
      { label: '温州市', value: '浙江省-温州市' },
      { label: '嘉兴市', value: '浙江省-嘉兴市' },
      { label: '湖州市', value: '浙江省-湖州市' },
      { label: '绍兴市', value: '浙江省-绍兴市' },
      { label: '金华市', value: '浙江省-金华市' },
      { label: '衢州市', value: '浙江省-衢州市' },
      { label: '舟山市', value: '浙江省-舟山市' },
      { label: '台州市', value: '浙江省-台州市' },
      { label: '丽水市', value: '浙江省-丽水市' },
    ],
  },
  {
    label: '江苏省',
    value: '江苏省',
    children: [
      {
        label: '南京市',
        value: '江苏省-南京市',
        children: [
          { label: '玄武区', value: '江苏省-南京市-玄武区' },
          { label: '秦淮区', value: '江苏省-南京市-秦淮区' },
          { label: '建邺区', value: '江苏省-南京市-建邺区' },
          { label: '鼓楼区', value: '江苏省-南京市-鼓楼区' },
          { label: '浦口区', value: '江苏省-南京市-浦口区' },
          { label: '栖霞区', value: '江苏省-南京市-栖霞区' },
          { label: '雨花台区', value: '江苏省-南京市-雨花台区' },
          { label: '江宁区', value: '江苏省-南京市-江宁区' },
          { label: '六合区', value: '江苏省-南京市-六合区' },
          { label: '溧水区', value: '江苏省-南京市-溧水区' },
          { label: '高淳区', value: '江苏省-南京市-高淳区' },
        ],
      },
      { label: '无锡市', value: '江苏省-无锡市' },
      { label: '徐州市', value: '江苏省-徐州市' },
      { label: '常州市', value: '江苏省-常州市' },
      { label: '苏州市', value: '江苏省-苏州市' },
      { label: '南通市', value: '江苏省-南通市' },
      { label: '连云港市', value: '江苏省-连云港市' },
      { label: '淮安市', value: '江苏省-淮安市' },
      { label: '盐城市', value: '江苏省-盐城市' },
      { label: '扬州市', value: '江苏省-扬州市' },
      { label: '镇江市', value: '江苏省-镇江市' },
      { label: '泰州市', value: '江苏省-泰州市' },
      { label: '宿迁市', value: '江苏省-宿迁市' },
    ],
  },
  {
    label: '四川省',
    value: '四川省',
    children: [
      {
        label: '成都市',
        value: '四川省-成都市',
        children: [
          { label: '锦江区', value: '四川省-成都市-锦江区' },
          { label: '青羊区', value: '四川省-成都市-青羊区' },
          { label: '金牛区', value: '四川省-成都市-金牛区' },
          { label: '武侯区', value: '四川省-成都市-武侯区' },
          { label: '成华区', value: '四川省-成都市-成华区' },
          { label: '龙泉驿区', value: '四川省-成都市-龙泉驿区' },
          { label: '青白江区', value: '四川省-成都市-青白江区' },
          { label: '新都区', value: '四川省-成都市-新都区' },
          { label: '温江区', value: '四川省-成都市-温江区' },
          { label: '双流区', value: '四川省-成都市-双流区' },
          { label: '郫都区', value: '四川省-成都市-郫都区' },
          { label: '新津区', value: '四川省-成都市-新津区' },
        ],
      },
      { label: '自贡市', value: '四川省-自贡市' },
      { label: '攀枝花市', value: '四川省-攀枝花市' },
      { label: '泸州市', value: '四川省-泸州市' },
      { label: '德阳市', value: '四川省-德阳市' },
      { label: '绵阳市', value: '四川省-绵阳市' },
      { label: '广元市', value: '四川省-广元市' },
      { label: '遂宁市', value: '四川省-遂宁市' },
      { label: '内江市', value: '四川省-内江市' },
      { label: '乐山市', value: '四川省-乐山市' },
      { label: '南充市', value: '四川省-南充市' },
      { label: '眉山市', value: '四川省-眉山市' },
      { label: '宜宾市', value: '四川省-宜宾市' },
      { label: '广安市', value: '四川省-广安市' },
      { label: '达州市', value: '四川省-达州市' },
      { label: '雅安市', value: '四川省-雅安市' },
      { label: '巴中市', value: '四川省-巴中市' },
      { label: '资阳市', value: '四川省-资阳市' },
    ],
  },
  {
    label: '湖北省',
    value: '湖北省',
    children: [
      {
        label: '武汉市',
        value: '湖北省-武汉市',
        children: [
          { label: '江岸区', value: '湖北省-武汉市-江岸区' },
          { label: '江汉区', value: '湖北省-武汉市-江汉区' },
          { label: '硚口区', value: '湖北省-武汉市-硚口区' },
          { label: '汉阳区', value: '湖北省-武汉市-汉阳区' },
          { label: '武昌区', value: '湖北省-武汉市-武昌区' },
          { label: '青山区', value: '湖北省-武汉市-青山区' },
          { label: '洪山区', value: '湖北省-武汉市-洪山区' },
          { label: '东西湖区', value: '湖北省-武汉市-东西湖区' },
          { label: '汉南区', value: '湖北省-武汉市-汉南区' },
          { label: '蔡甸区', value: '湖北省-武汉市-蔡甸区' },
          { label: '江夏区', value: '湖北省-武汉市-江夏区' },
          { label: '黄陂区', value: '湖北省-武汉市-黄陂区' },
          { label: '新洲区', value: '湖北省-武汉市-新洲区' },
        ],
      },
      { label: '黄石市', value: '湖北省-黄石市' },
      { label: '十堰市', value: '湖北省-十堰市' },
      { label: '宜昌市', value: '湖北省-宜昌市' },
      { label: '襄阳市', value: '湖北省-襄阳市' },
      { label: '鄂州市', value: '湖北省-鄂州市' },
      { label: '荆门市', value: '湖北省-荆门市' },
      { label: '孝感市', value: '湖北省-孝感市' },
      { label: '荆州市', value: '湖北省-荆州市' },
      { label: '黄冈市', value: '湖北省-黄冈市' },
      { label: '咸宁市', value: '湖北省-咸宁市' },
      { label: '随州市', value: '湖北省-随州市' },
      { label: '恩施土家族苗族自治州', value: '湖北省-恩施土家族苗族自治州' },
    ],
  },
  {
    label: '湖南省',
    value: '湖南省',
    children: [
      { label: '长沙市', value: '湖南省-长沙市' },
      { label: '株洲市', value: '湖南省-株洲市' },
      { label: '湘潭市', value: '湖南省-湘潭市' },
      { label: '衡阳市', value: '湖南省-衡阳市' },
      { label: '邵阳市', value: '湖南省-邵阳市' },
      { label: '岳阳市', value: '湖南省-岳阳市' },
      { label: '常德市', value: '湖南省-常德市' },
      { label: '张家界市', value: '湖南省-张家界市' },
      { label: '益阳市', value: '湖南省-益阳市' },
      { label: '郴州市', value: '湖南省-郴州市' },
      { label: '永州市', value: '湖南省-永州市' },
      { label: '怀化市', value: '湖南省-怀化市' },
      { label: '娄底市', value: '湖南省-娄底市' },
      { label: '湘西土家族苗族自治州', value: '湖南省-湘西土家族苗族自治州' },
    ],
  },
  {
    label: '河南省',
    value: '河南省',
    children: [
      { label: '郑州市', value: '河南省-郑州市' },
      { label: '开封市', value: '河南省-开封市' },
      { label: '洛阳市', value: '河南省-洛阳市' },
      { label: '平顶山市', value: '河南省-平顶山市' },
      { label: '安阳市', value: '河南省-安阳市' },
      { label: '鹤壁市', value: '河南省-鹤壁市' },
      { label: '新乡市', value: '河南省-新乡市' },
      { label: '焦作市', value: '河南省-焦作市' },
      { label: '濮阳市', value: '河南省-濮阳市' },
      { label: '许昌市', value: '河南省-许昌市' },
      { label: '漯河市', value: '河南省-漯河市' },
      { label: '三门峡市', value: '河南省-三门峡市' },
      { label: '南阳市', value: '河南省-南阳市' },
      { label: '商丘市', value: '河南省-商丘市' },
      { label: '信阳市', value: '河南省-信阳市' },
      { label: '周口市', value: '河南省-周口市' },
      { label: '驻马店市', value: '河南省-驻马店市' },
      { label: '济源市', value: '河南省-济源市' },
    ],
  },
  {
    label: '山东省',
    value: '山东省',
    children: [
      { label: '济南市', value: '山东省-济南市' },
      { label: '青岛市', value: '山东省-青岛市' },
      { label: '淄博市', value: '山东省-淄博市' },
      { label: '枣庄市', value: '山东省-枣庄市' },
      { label: '东营市', value: '山东省-东营市' },
      { label: '烟台市', value: '山东省-烟台市' },
      { label: '潍坊市', value: '山东省-潍坊市' },
      { label: '济宁市', value: '山东省-济宁市' },
      { label: '泰安市', value: '山东省-泰安市' },
      { label: '威海市', value: '山东省-威海市' },
      { label: '日照市', value: '山东省-日照市' },
      { label: '临沂市', value: '山东省-临沂市' },
      { label: '德州市', value: '山东省-德州市' },
      { label: '聊城市', value: '山东省-聊城市' },
      { label: '滨州市', value: '山东省-滨州市' },
      { label: '菏泽市', value: '山东省-菏泽市' },
    ],
  },
  {
    label: '河北省',
    value: '河北省',
    children: [
      { label: '石家庄市', value: '河北省-石家庄市' },
      { label: '唐山市', value: '河北省-唐山市' },
      { label: '秦皇岛市', value: '河北省-秦皇岛市' },
      { label: '邯郸市', value: '河北省-邯郸市' },
      { label: '邢台市', value: '河北省-邢台市' },
      { label: '保定市', value: '河北省-保定市' },
      { label: '张家口市', value: '河北省-张家口市' },
      { label: '承德市', value: '河北省-承德市' },
      { label: '沧州市', value: '河北省-沧州市' },
      { label: '廊坊市', value: '河北省-廊坊市' },
      { label: '衡水市', value: '河北省-衡水市' },
    ],
  },
  {
    label: '山西省',
    value: '山西省',
    children: [
      { label: '太原市', value: '山西省-太原市' },
      { label: '大同市', value: '山西省-大同市' },
      { label: '阳泉市', value: '山西省-阳泉市' },
      { label: '长治市', value: '山西省-长治市' },
      { label: '晋城市', value: '山西省-晋城市' },
      { label: '朔州市', value: '山西省-朔州市' },
      { label: '晋中市', value: '山西省-晋中市' },
      { label: '运城市', value: '山西省-运城市' },
      { label: '忻州市', value: '山西省-忻州市' },
      { label: '临汾市', value: '山西省-临汾市' },
      { label: '吕梁市', value: '山西省-吕梁市' },
    ],
  },
  {
    label: '陕西省',
    value: '陕西省',
    children: [
      { label: '西安市', value: '陕西省-西安市' },
      { label: '铜川市', value: '陕西省-铜川市' },
      { label: '宝鸡市', value: '陕西省-宝鸡市' },
      { label: '咸阳市', value: '陕西省-咸阳市' },
      { label: '渭南市', value: '陕西省-渭南市' },
      { label: '延安市', value: '陕西省-延安市' },
      { label: '汉中市', value: '陕西省-汉中市' },
      { label: '榆林市', value: '陕西省-榆林市' },
      { label: '安康市', value: '陕西省-安康市' },
      { label: '商洛市', value: '陕西省-商洛市' },
    ],
  },
  {
    label: '辽宁省',
    value: '辽宁省',
    children: [
      { label: '沈阳市', value: '辽宁省-沈阳市' },
      { label: '大连市', value: '辽宁省-大连市' },
      { label: '鞍山市', value: '辽宁省-鞍山市' },
      { label: '抚顺市', value: '辽宁省-抚顺市' },
      { label: '本溪市', value: '辽宁省-本溪市' },
      { label: '丹东市', value: '辽宁省-丹东市' },
      { label: '锦州市', value: '辽宁省-锦州市' },
      { label: '营口市', value: '辽宁省-营口市' },
      { label: '阜新市', value: '辽宁省-阜新市' },
      { label: '辽阳市', value: '辽宁省-辽阳市' },
      { label: '盘锦市', value: '辽宁省-盘锦市' },
      { label: '铁岭市', value: '辽宁省-铁岭市' },
      { label: '朝阳市', value: '辽宁省-朝阳市' },
      { label: '葫芦岛市', value: '辽宁省-葫芦岛市' },
    ],
  },
  {
    label: '吉林省',
    value: '吉林省',
    children: [
      { label: '长春市', value: '吉林省-长春市' },
      { label: '吉林市', value: '吉林省-吉林市' },
      { label: '四平市', value: '吉林省-四平市' },
      { label: '辽源市', value: '吉林省-辽源市' },
      { label: '通化市', value: '吉林省-通化市' },
      { label: '白山市', value: '吉林省-白山市' },
      { label: '松原市', value: '吉林省-松原市' },
      { label: '白城市', value: '吉林省-白城市' },
      { label: '延边朝鲜族自治州', value: '吉林省-延边朝鲜族自治州' },
    ],
  },
  {
    label: '黑龙江省',
    value: '黑龙江省',
    children: [
      { label: '哈尔滨市', value: '黑龙江省-哈尔滨市' },
      { label: '齐齐哈尔市', value: '黑龙江省-齐齐哈尔市' },
      { label: '鸡西市', value: '黑龙江省-鸡西市' },
      { label: '鹤岗市', value: '黑龙江省-鹤岗市' },
      { label: '双鸭山市', value: '黑龙江省-双鸭山市' },
      { label: '大庆市', value: '黑龙江省-大庆市' },
      { label: '伊春市', value: '黑龙江省-伊春市' },
      { label: '佳木斯市', value: '黑龙江省-佳木斯市' },
      { label: '七台河市', value: '黑龙江省-七台河市' },
      { label: '牡丹江市', value: '黑龙江省-牡丹江市' },
      { label: '黑河市', value: '黑龙江省-黑河市' },
      { label: '绥化市', value: '黑龙江省-绥化市' },
      { label: '大兴安岭地区', value: '黑龙江省-大兴安岭地区' },
    ],
  },
  {
    label: '安徽省',
    value: '安徽省',
    children: [
      { label: '合肥市', value: '安徽省-合肥市' },
      { label: '芜湖市', value: '安徽省-芜湖市' },
      { label: '蚌埠市', value: '安徽省-蚌埠市' },
      { label: '淮南市', value: '安徽省-淮南市' },
      { label: '马鞍山市', value: '安徽省-马鞍山市' },
      { label: '淮北市', value: '安徽省-淮北市' },
      { label: '铜陵市', value: '安徽省-铜陵市' },
      { label: '安庆市', value: '安徽省-安庆市' },
      { label: '黄山市', value: '安徽省-黄山市' },
      { label: '滁州市', value: '安徽省-滁州市' },
      { label: '阜阳市', value: '安徽省-阜阳市' },
      { label: '宿州市', value: '安徽省-宿州市' },
      { label: '六安市', value: '安徽省-六安市' },
      { label: '亳州市', value: '安徽省-亳州市' },
      { label: '池州市', value: '安徽省-池州市' },
      { label: '宣城市', value: '安徽省-宣城市' },
    ],
  },
  {
    label: '福建省',
    value: '福建省',
    children: [
      { label: '福州市', value: '福建省-福州市' },
      { label: '厦门市', value: '福建省-厦门市' },
      { label: '莆田市', value: '福建省-莆田市' },
      { label: '三明市', value: '福建省-三明市' },
      { label: '泉州市', value: '福建省-泉州市' },
      { label: '漳州市', value: '福建省-漳州市' },
      { label: '南平市', value: '福建省-南平市' },
      { label: '龙岩市', value: '福建省-龙岩市' },
      { label: '宁德市', value: '福建省-宁德市' },
    ],
  },
  {
    label: '江西省',
    value: '江西省',
    children: [
      { label: '南昌市', value: '江西省-南昌市' },
      { label: '景德镇市', value: '江西省-景德镇市' },
      { label: '萍乡市', value: '江西省-萍乡市' },
      { label: '九江市', value: '江西省-九江市' },
      { label: '新余市', value: '江西省-新余市' },
      { label: '鹰潭市', value: '江西省-鹰潭市' },
      { label: '赣州市', value: '江西省-赣州市' },
      { label: '吉安市', value: '江西省-吉安市' },
      { label: '宜春市', value: '江西省-宜春市' },
      { label: '抚州市', value: '江西省-抚州市' },
      { label: '上饶市', value: '江西省-上饶市' },
    ],
  },
  {
    label: '云南省',
    value: '云南省',
    children: [
      { label: '昆明市', value: '云南省-昆明市' },
      { label: '曲靖市', value: '云南省-曲靖市' },
      { label: '玉溪市', value: '云南省-玉溪市' },
      { label: '保山市', value: '云南省-保山市' },
      { label: '昭通市', value: '云南省-昭通市' },
      { label: '丽江市', value: '云南省-丽江市' },
      { label: '普洱市', value: '云南省-普洱市' },
      { label: '临沧市', value: '云南省-临沧市' },
      { label: '楚雄彝族自治州', value: '云南省-楚雄彝族自治州' },
      { label: '红河哈尼族彝族自治州', value: '云南省-红河哈尼族彝族自治州' },
      { label: '文山壮族苗族自治州', value: '云南省-文山壮族苗族自治州' },
      { label: '西双版纳傣族自治州', value: '云南省-西双版纳傣族自治州' },
      { label: '大理白族自治州', value: '云南省-大理白族自治州' },
      { label: '德宏傣族景颇族自治州', value: '云南省-德宏傣族景颇族自治州' },
      { label: '怒江傈僳族自治州', value: '云南省-怒江傈僳族自治州' },
      { label: '迪庆藏族自治州', value: '云南省-迪庆藏族自治州' },
    ],
  },
  {
    label: '贵州省',
    value: '贵州省',
    children: [
      { label: '贵阳市', value: '贵州省-贵阳市' },
      { label: '六盘水市', value: '贵州省-六盘水市' },
      { label: '遵义市', value: '贵州省-遵义市' },
      { label: '安顺市', value: '贵州省-安顺市' },
      { label: '毕节市', value: '贵州省-毕节市' },
      { label: '铜仁市', value: '贵州省-铜仁市' },
      { label: '黔西南布依族苗族自治州', value: '贵州省-黔西南布依族苗族自治州' },
      { label: '黔东南苗族侗族自治州', value: '贵州省-黔东南苗族侗族自治州' },
      { label: '黔南布依族苗族自治州', value: '贵州省-黔南布依族苗族自治州' },
    ],
  },
  {
    label: '广西壮族自治区',
    value: '广西壮族自治区',
    children: [
      { label: '南宁市', value: '广西壮族自治区-南宁市' },
      { label: '柳州市', value: '广西壮族自治区-柳州市' },
      { label: '桂林市', value: '广西壮族自治区-桂林市' },
      { label: '梧州市', value: '广西壮族自治区-梧州市' },
      { label: '北海市', value: '广西壮族自治区-北海市' },
      { label: '防城港市', value: '广西壮族自治区-防城港市' },
      { label: '钦州市', value: '广西壮族自治区-钦州市' },
      { label: '贵港市', value: '广西壮族自治区-贵港市' },
      { label: '玉林市', value: '广西壮族自治区-玉林市' },
      { label: '百色市', value: '广西壮族自治区-百色市' },
      { label: '贺州市', value: '广西壮族自治区-贺州市' },
      { label: '河池市', value: '广西壮族自治区-河池市' },
      { label: '来宾市', value: '广西壮族自治区-来宾市' },
      { label: '崇左市', value: '广西壮族自治区-崇左市' },
    ],
  },
  {
    label: '海南省',
    value: '海南省',
    children: [
      { label: '海口市', value: '海南省-海口市' },
      { label: '三亚市', value: '海南省-三亚市' },
      { label: '三沙市', value: '海南省-三沙市' },
      { label: '儋州市', value: '海南省-儋州市' },
    ],
  },
  {
    label: '重庆市',
    value: '重庆市',
    children: [
      { label: '万州区', value: '重庆市-万州区' },
      { label: '涪陵区', value: '重庆市-涪陵区' },
      { label: '渝中区', value: '重庆市-渝中区' },
      { label: '大渡口区', value: '重庆市-大渡口区' },
      { label: '江北区', value: '重庆市-江北区' },
      { label: '沙坪坝区', value: '重庆市-沙坪坝区' },
      { label: '九龙坡区', value: '重庆市-九龙坡区' },
      { label: '南岸区', value: '重庆市-南岸区' },
      { label: '北碚区', value: '重庆市-北碚区' },
      { label: '綦江区', value: '重庆市-綦江区' },
      { label: '大足区', value: '重庆市-大足区' },
      { label: '渝北区', value: '重庆市-渝北区' },
      { label: '巴南区', value: '重庆市-巴南区' },
      { label: '黔江区', value: '重庆市-黔江区' },
      { label: '长寿区', value: '重庆市-长寿区' },
      { label: '江津区', value: '重庆市-江津区' },
      { label: '合川区', value: '重庆市-合川区' },
      { label: '永川区', value: '重庆市-永川区' },
      { label: '南川区', value: '重庆市-南川区' },
      { label: '璧山区', value: '重庆市-璧山区' },
      { label: '铜梁区', value: '重庆市-铜梁区' },
      { label: '潼南区', value: '重庆市-潼南区' },
      { label: '荣昌区', value: '重庆市-荣昌区' },
      { label: '开州区', value: '重庆市-开州区' },
      { label: '梁平区', value: '重庆市-梁平区' },
      { label: '武隆区', value: '重庆市-武隆区' },
    ],
  },
  {
    label: '天津市',
    value: '天津市',
    children: [
      { label: '和平区', value: '天津市-和平区' },
      { label: '河东区', value: '天津市-河东区' },
      { label: '河西区', value: '天津市-河西区' },
      { label: '南开区', value: '天津市-南开区' },
      { label: '河北区', value: '天津市-河北区' },
      { label: '红桥区', value: '天津市-红桥区' },
      { label: '东丽区', value: '天津市-东丽区' },
      { label: '西青区', value: '天津市-西青区' },
      { label: '津南区', value: '天津市-津南区' },
      { label: '北辰区', value: '天津市-北辰区' },
      { label: '武清区', value: '天津市-武清区' },
      { label: '宝坻区', value: '天津市-宝坻区' },
      { label: '滨海新区', value: '天津市-滨海新区' },
      { label: '宁河区', value: '天津市-宁河区' },
      { label: '静海区', value: '天津市-静海区' },
      { label: '蓟州区', value: '天津市-蓟州区' },
    ],
  },
  {
    label: '内蒙古自治区',
    value: '内蒙古自治区',
    children: [
      { label: '呼和浩特市', value: '内蒙古自治区-呼和浩特市' },
      { label: '包头市', value: '内蒙古自治区-包头市' },
      { label: '乌海市', value: '内蒙古自治区-乌海市' },
      { label: '赤峰市', value: '内蒙古自治区-赤峰市' },
      { label: '通辽市', value: '内蒙古自治区-通辽市' },
      { label: '鄂尔多斯市', value: '内蒙古自治区-鄂尔多斯市' },
      { label: '呼伦贝尔市', value: '内蒙古自治区-呼伦贝尔市' },
      { label: '巴彦淖尔市', value: '内蒙古自治区-巴彦淖尔市' },
      { label: '乌兰察布市', value: '内蒙古自治区-乌兰察布市' },
      { label: '兴安盟', value: '内蒙古自治区-兴安盟' },
      { label: '锡林郭勒盟', value: '内蒙古自治区-锡林郭勒盟' },
      { label: '阿拉善盟', value: '内蒙古自治区-阿拉善盟' },
    ],
  },
  {
    label: '新疆维吾尔自治区',
    value: '新疆维吾尔自治区',
    children: [
      { label: '乌鲁木齐市', value: '新疆维吾尔自治区-乌鲁木齐市' },
      { label: '克拉玛依市', value: '新疆维吾尔自治区-克拉玛依市' },
      { label: '吐鲁番市', value: '新疆维吾尔自治区-吐鲁番市' },
      { label: '哈密市', value: '新疆维吾尔自治区-哈密市' },
      { label: '昌吉回族自治州', value: '新疆维吾尔自治区-昌吉回族自治州' },
      { label: '博尔塔拉蒙古自治州', value: '新疆维吾尔自治区-博尔塔拉蒙古自治州' },
      { label: '巴音郭楞蒙古自治州', value: '新疆维吾尔自治区-巴音郭楞蒙古自治州' },
      { label: '阿克苏地区', value: '新疆维吾尔自治区-阿克苏地区' },
      { label: '克孜勒苏柯尔克孜自治州', value: '新疆维吾尔自治区-克孜勒苏柯尔克孜自治州' },
      { label: '喀什地区', value: '新疆维吾尔自治区-喀什地区' },
      { label: '和田地区', value: '新疆维吾尔自治区-和田地区' },
      { label: '伊犁哈萨克自治州', value: '新疆维吾尔自治区-伊犁哈萨克自治州' },
      { label: '塔城地区', value: '新疆维吾尔自治区-塔城地区' },
      { label: '阿勒泰地区', value: '新疆维吾尔自治区-阿勒泰地区' },
    ],
  },
  {
    label: '西藏自治区',
    value: '西藏自治区',
    children: [
      { label: '拉萨市', value: '西藏自治区-拉萨市' },
      { label: '日喀则市', value: '西藏自治区-日喀则市' },
      { label: '昌都市', value: '西藏自治区-昌都市' },
      { label: '林芝市', value: '西藏自治区-林芝市' },
      { label: '山南市', value: '西藏自治区-山南市' },
      { label: '那曲市', value: '西藏自治区-那曲市' },
      { label: '阿里地区', value: '西藏自治区-阿里地区' },
    ],
  },
  {
    label: '宁夏回族自治区',
    value: '宁夏回族自治区',
    children: [
      { label: '银川市', value: '宁夏回族自治区-银川市' },
      { label: '石嘴山市', value: '宁夏回族自治区-石嘴山市' },
      { label: '吴忠市', value: '宁夏回族自治区-吴忠市' },
      { label: '固原市', value: '宁夏回族自治区-固原市' },
      { label: '中卫市', value: '宁夏回族自治区-中卫市' },
    ],
  },
  {
    label: '青海省',
    value: '青海省',
    children: [
      { label: '西宁市', value: '青海省-西宁市' },
      { label: '海东市', value: '青海省-海东市' },
      { label: '海北藏族自治州', value: '青海省-海北藏族自治州' },
      { label: '黄南藏族自治州', value: '青海省-黄南藏族自治州' },
      { label: '海南藏族自治州', value: '青海省-海南藏族自治州' },
      { label: '果洛藏族自治州', value: '青海省-果洛藏族自治州' },
      { label: '玉树藏族自治州', value: '青海省-玉树藏族自治州' },
      { label: '海西蒙古族藏族自治州', value: '青海省-海西蒙古族藏族自治州' },
    ],
  },
  {
    label: '甘肃省',
    value: '甘肃省',
    children: [
      { label: '兰州市', value: '甘肃省-兰州市' },
      { label: '嘉峪关市', value: '甘肃省-嘉峪关市' },
      { label: '金昌市', value: '甘肃省-金昌市' },
      { label: '白银市', value: '甘肃省-白银市' },
      { label: '天水市', value: '甘肃省-天水市' },
      { label: '武威市', value: '甘肃省-武威市' },
      { label: '张掖市', value: '甘肃省-张掖市' },
      { label: '平凉市', value: '甘肃省-平凉市' },
      { label: '酒泉市', value: '甘肃省-酒泉市' },
      { label: '庆阳市', value: '甘肃省-庆阳市' },
      { label: '定西市', value: '甘肃省-定西市' },
      { label: '陇南市', value: '甘肃省-陇南市' },
      { label: '临夏回族自治州', value: '甘肃省-临夏回族自治州' },
      { label: '甘南藏族自治州', value: '甘肃省-甘南藏族自治州' },
    ],
  },
  {
    label: '香港特别行政区',
    value: '香港特别行政区',
    children: [
      { label: '中西区', value: '香港特别行政区-中西区' },
      { label: '东区', value: '香港特别行政区-东区' },
      { label: '南区', value: '香港特别行政区-南区' },
      { label: '湾仔区', value: '香港特别行政区-湾仔区' },
      { label: '九龙城区', value: '香港特别行政区-九龙城区' },
      { label: '观塘区', value: '香港特别行政区-观塘区' },
      { label: '深水埗区', value: '香港特别行政区-深水埗区' },
      { label: '黄大仙区', value: '香港特别行政区-黄大仙区' },
      { label: '油尖旺区', value: '香港特别行政区-油尖旺区' },
      { label: '离岛区', value: '香港特别行政区-离岛区' },
      { label: '葵青区', value: '香港特别行政区-葵青区' },
      { label: '北区', value: '香港特别行政区-北区' },
      { label: '西贡区', value: '香港特别行政区-西贡区' },
      { label: '沙田区', value: '香港特别行政区-沙田区' },
      { label: '大埔区', value: '香港特别行政区-大埔区' },
      { label: '荃湾区', value: '香港特别行政区-荃湾区' },
      { label: '屯门区', value: '香港特别行政区-屯门区' },
      { label: '元朗区', value: '香港特别行政区-元朗区' },
    ],
  },
  {
    label: '澳门特别行政区',
    value: '澳门特别行政区',
    children: [
      { label: '澳门半岛', value: '澳门特别行政区-澳门半岛' },
      { label: '氹仔', value: '澳门特别行政区-氹仔' },
      { label: '路环', value: '澳门特别行政区-路环' },
    ],
  },
  {
    label: '台湾省',
    value: '台湾省',
    children: [
      { label: '台北市', value: '台湾省-台北市' },
      { label: '新北市', value: '台湾省-新北市' },
      { label: '桃园市', value: '台湾省-桃园市' },
      { label: '台中市', value: '台湾省-台中市' },
      { label: '台南市', value: '台湾省-台南市' },
      { label: '高雄市', value: '台湾省-高雄市' },
      { label: '基隆市', value: '台湾省-基隆市' },
      { label: '新竹市', value: '台湾省-新竹市' },
      { label: '嘉义市', value: '台湾省-嘉义市' },
      { label: '新竹县', value: '台湾省-新竹县' },
      { label: '苗栗县', value: '台湾省-苗栗县' },
      { label: '彰化县', value: '台湾省-彰化县' },
      { label: '南投县', value: '台湾省-南投县' },
      { label: '云林县', value: '台湾省-云林县' },
      { label: '嘉义县', value: '台湾省-嘉义县' },
      { label: '屏东县', value: '台湾省-屏东县' },
      { label: '宜兰县', value: '台湾省-宜兰县' },
      { label: '花莲县', value: '台湾省-花莲县' },
      { label: '台东县', value: '台湾省-台东县' },
      { label: '澎湖县', value: '台湾省-澎湖县' },
      { label: '金门县', value: '台湾省-金门县' },
      { label: '连江县', value: '台湾省-连江县' },
    ],
  },
]
